<?xml version="1.0" encoding="utf-8"?><Database Name="phongDB" Class="avbDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=phongDB.db.10329167.hostedresource.com;Initial Catalog=phongDB;Persist Security Info=True;User ID=phongDB" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="phongDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.avb_content" Member="avb_contents">
    <Type Name="avb_content">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="page" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="text_content" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.avb_contact" Member="avb_contacts">
    <Type Name="avb_contact">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="topic" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="message" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="newsletter" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>